In [2]:
#Imports
import numpy as np
import random as rnd

def Wash():
    m = 20
    x = []
    y = []
    z = []
    
    #loop to store numbers between 0 and 1 to the array
    for i in range (0,m):
        
        x.append(rnd.uniform(0,1))
        y.append(rnd.uniform(0,1))
        z.append(rnd.uniform(0,1))
    
    xyz = np.asarray((x,y,z))
    Arr = np.transpose(xyz)
    print (Arr,)
    
    
    
    for i in range (0,10):
        
        #Balance with color white
        Arr[:][:][i] = ((Arr[:][:][i]+1)/2)
        
    return Arr

Final = Wash ()

print (Final)

[[ 0.88550455  0.42358629  0.63901361]
 [ 0.36787184  0.98398799  0.02609708]
 [ 0.21080563  0.51722103  0.93490647]
 [ 0.66474949  0.51540994  0.5508393 ]
 [ 0.49022703  0.4510065   0.1005754 ]
 [ 0.43991687  0.86770882  0.58850139]
 [ 0.13299531  0.05610672  0.56345967]
 [ 0.74391624  0.59291952  0.77419585]
 [ 0.9543389   0.01911073  0.49757543]
 [ 0.61084454  0.53717412  0.51369516]
 [ 0.79951053  0.89690906  0.13144804]
 [ 0.82849178  0.54856149  0.53942168]
 [ 0.52934581  0.63177126  0.31715637]
 [ 0.94144407  0.03107846  0.48172141]
 [ 0.76731493  0.15619117  0.33343505]
 [ 0.28052288  0.8588832   0.99991141]
 [ 0.67446362  0.20882689  0.61331185]
 [ 0.92811467  0.77121746  0.52384528]
 [ 0.10530036  0.23589584  0.28049376]
 [ 0.53326261  0.10932126  0.89486773]]
[[ 0.94275228  0.71179314  0.81950681]
 [ 0.68393592  0.99199399  0.51304854]
 [ 0.60540282  0.75861051  0.96745323]
 [ 0.83237474  0.75770497  0.77541965]
 [ 0.74511351  0.72550325  0.5502877 ]
 [ 0.71995843  0.9338544